kind: List
apiVersion: v1
items:
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: category
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: category
      spec:
        containers:
        - name: category
          image: reactivesw/category:0.0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: server_port
            value: "80"
          - name: spring_datasource_url
            value: jdbc:postgresql://pg-data/category
          - name: spring_cloud_config_uri
            value: http://reactivesw-config
          - name: jwt_secret
            valueFrom:
              secretKeyRef:
              name: reactivesw-secret
              key: jwt.secret
- kind: Service
  apiVersion: v1
  metadata:
    name: category
    labels:
      name: category
  spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
    selector:
      name: category

