apiVersion: v1
kind: Service
metadata:
  name: category
  labels:
    name: category
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30003
  selector:
    name: category
