server:
  port: 8082

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/category
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: io.reactivesw.database.dialect.JSONBPostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update

io:
  reactivesw:
    message:
      brokerType: google
      google:
        project:
          id: reactivesw-project
      topic:
        deletecategory:
          name: "reactivesw-dev-category-deleted"
          version: 1